{% set name = "argh" %}
{% set version = "0.31.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f30023d8be14ca5ee6b1b3eeab829151d7bbda464ae07dc4dd5347919c5892f9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python
  run_constrained:
    - argcomplete >=2.0

test:
  source_files:
    - tests
  imports:
    - argh
    - argh.assembling
    - argh.completion
    - argh.constants
    - argh.dispatching
    - argh.dto
    - argh.exceptions
    - argh.utils
  requires:
    - pip
    - pytest >=7.4
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -v --tb=short tests

about:
  home: https://github.com/neithere/argh
  license: LGPL-3.0-or-later
  license_file:
    - COPYING.LESSER
    - COPYING
  license_family: LGPL
  summary: An unobtrusive argparse wrapper with natural syntax
  description: |
    An argparse wrapper that doesn't make you say "argh" each time you deal with it.
  doc_url: https://argh.readthedocs.io
  dev_url: https://github.com/neithere/argh

extra:
  recipe-maintainers:
    - goanpeca
    - daler
