{% set name = "argh" %}
{% set version = "0.29.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/argh-{{ version }}.tar.gz
  sha256: 695c0ae4534270cae2697841b4a56f434a990694a00264ea10ebbbcdc02c13f7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python

test:
  imports:
    - argh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neithere/argh
  license: LGPL-3.0
  license_file:
    - COPYING.LESSER
    - COPYING
  license_family: LGPL
  summary: An unobtrusive argparse wrapper with natural syntax
  description: |
    An argparse wrapper that doesn't make you say "argh" each time you deal with it.
  doc_url: https://argh.readthedocs.io
  dev_url: https://github.com/neithere/argh

extra:
  recipe-maintainers:
    - goanpeca
    - daler
