{% set name = "argh" %}
{% set version = "0.28.1" %}
{% set hash_type = "sha256" %}
{% set hash = "b2093086f0e809a3ecc24b64a2145309ee8f56d034936cd59e57c558a357329d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - argparse >=1.1  # [py26]

test:
  imports:
    - argh

about:
  home: https://github.com/neithere/argh
  license: LGPL 3
  summary: The Natural CLI.
  description: |
    An argparse wrapper that doesn't make you say "argh" each time you deal with it.
  doc_url: http://argh.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
    - daler
