travis:
  secure:
    BINSTAR_TOKEN: oJdyFWR+xuaseWd4MiMZL7MuAR+iI1SDIwbkmFkcxT4rAnibL431ro55CBSJ4sVbxsPSMEP8ukjMINDhT0giZpW15cG+O/bqNlR8wd2b8PZ9z5xJd3eRTRC7b+oEZ1xPF1OqdQ70zL49IJyB52DWoUGSh2YY3BagKhyRccfNrDi2ErfanzRTp88oDYnSKpB3c+MtlXej5AEgShZA4Mo7q8P7Prhs8q0sAxqo+d/6w+ErSMAtr71cBi4pclNbrHAIzqk5vfpsrJh+YpHzk/t+iVUbszCRh5vVeco7oCZfVCqPOiQw0yK7xCgg/o1o1NUEr/rDKZ28ATEQ9dND5wYOfTDFqmJMQuNhjDe+1FUQDZlN80dGxVsc7GTbbmoJup7wKROA6qRgvFiwdi0Ff80dCHREXZ81FmI/IfyDSNhr6Jd71JC7wJ5HM1iXWApkilMqx9SXjhulDVU8Np/XmSQFD6UqJhpqz6W2F7Wx0sX4XeKNczMgfsuRWEiX5+oSRr3cW2pDbAqK/sB0Jnu5gI5p5pp5gGDMkpnGhnI8KOeh1SXHylkn8ZvcoN8bc2zxfsELA7zPcsew28m2W5utJACCZ6Fg2yp1D3f/xCLsZFL7MaOI9eye+wtNBgftqplec+XqK03G4kjegAXl1q+yqsckYMzvAx4a6kf5ncgl4OGOwkg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
